CREATE TABLE `materiel` (
  `idmateriel` bigint NOT NULL AUTO_INCREMENT,
  `uuid` varchar(45) NOT NULL,
  `time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Inbound time or input to database time  or timeline',
  `name` varchar(100) NOT NULL,
  `type` varchar(45) NOT NULL COMMENT 'Category',
  `barcode` varchar(45) NOT NULL COMMENT 'Bar code',
  `serial_number` varchar(45) NOT NULL,
  `part_number` varchar(45) NOT NULL,
  `date_code` varchar(45) NOT NULL,
  `inbound_quantity` double NOT NULL DEFAULT '0' COMMENT 'Inbound quantity',
  `cost_price` decimal(12,2) DEFAULT NULL COMMENT 'Cost price',
  `total_cost` decimal(20,2) DEFAULT NULL COMMENT 'total_cost = inbound_quantity *  cost_price',
  `price` decimal(12,2) DEFAULT NULL COMMENT 'Selling price or Current price  ',
  `manufacturer` varchar(450) DEFAULT NULL,
  `manufacture_date` datetime DEFAULT NULL COMMENT 'Production date ,Date of manufacture',
  `life_date` datetime DEFAULT NULL COMMENT 'Shelf life  or expiration data',
  `location` varchar(450) NOT NULL COMMENT 'where is location ',
  `owner` varchar(45) DEFAULT NULL COMMENT 'Who Owner',
  `from` varchar(45) DEFAULT NULL COMMENT 'owner or address ',
  `to` varchar(45) DEFAULT NULL COMMENT 'owner or address ',
  `how` varchar(45) DEFAULT NULL COMMENT 'how from to owner or Logistics tracking number',
  `who` varchar(45) DEFAULT NULL COMMENT 'who is recoder ',
  `what` varchar(450) DEFAULT NULL COMMENT 'What is the purpose of the material',
  `when` datetime DEFAULT NULL,
  `where` varchar(45) DEFAULT NULL,
  `why` varchar(45) DEFAULT NULL COMMENT 'point why database uuid',
  `action` varchar(45) DEFAULT NULL COMMENT 'buy sell  input output ',
  `country` varchar(45) DEFAULT NULL COMMENT 'The country where the material was produced',
  `url` varchar(450) DEFAULT NULL COMMENT 'site url',
  `status` varchar(45) NOT NULL COMMENT 'Stock Status',
  `remark` varchar(450) DEFAULT NULL,
  `priority` int NOT NULL DEFAULT '0',
  `partial` varchar(45) DEFAULT NULL COMMENT 'Define a material belongs to product',
  PRIMARY KEY (`idmateriel`,`uuid`,`time`,`name`,`type`,`barcode`,`serial_number`,`part_number`,`date_code`,`priority`),
  UNIQUE KEY `idmateriel_UNIQUE` (`idmateriel`),
  UNIQUE KEY `uuid_UNIQUE` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;